### ISSUE TITLE
Add buildable spacecraft

### ISSUE THREAD

**Issue by aerkiaga** [aerkiaga/nodeverse#13]
This issue should be closed once it is possible for the player to physically build a spaceship out of nodes, then board it and fly on it as attached to an entity.

- [x] Add basic node/entity conversion, mounting
- [x] Add a few actual spaceship nodes
- [x] Add more customization
- [x] Update example game to account for the new mechanics

**Comment by corarona** [comment]
Wow this whole thing sounds great. I will certainly try it later when i get home. In the meantime regarding the rockets i think meshnode might be exactly what you're looking for even though the mod itsself seems to be unmaintained we're currently in the process of porting it to mineclonia (while preserving compatibility to mtg) https://git.minetest.land/Mineclonia/mcl_meshnode

I might contribute a line or 2 in the future. I think this is a great idea!

**Comment by corarona** [comment]
Tried it and it's some amazing stuff already even though the "planets" are a bit close together i feel. 

I tried loading the meshnode mod but the player_api thing you use seems to be quite different from default and mcl_player :/ couldnt easily make it work. But i'll investigate further.

Sadly, as far as I see actual planets (as in spheres) with somewhat realistic gravity are off the table with mt so i do kinda like your approach in general.

**Comment by corarona** [comment]
Btw. the cloud is not infinite as the readme states - it's quite finite actually. It goes about 31000 nodes in all directions from 0,0,0

**Comment by aerkiaga** [comment]
Hi, I'm glad you like what's currently on the table. There's a new planet layout planned for 0.3 ;) Something like outer space between them, more realistic. Will have to investigate on that front after finishing this part. And yeah, I should probably word the README differently...

**Comment by aerkiaga** [comment]
I should at least modify the layout in 0.2, so it's a more interesting experience... Also, while most of the base code is done, is fails with node removal on some edge cases, like placing 2 or 3 disconnected nodes in an empty node's Moore neighborhood, then placing the middle node and finally removing it.
