### ISSUE TITLE
Star Trek seats?

### ISSUE THREAD

**Issue by aerkiaga** [aerkiaga/nodeverse#14]
![Discord message asking for this feature](https://satoshiupload.com/images/KMM3h7DuJ4.png)

I haven't even watched Star Trek... Searching the web affords multiple variants of the aforementioned chair. Anybody can help?

**Comment by ExeVirus** [comment]
Don't, it's copyrighted, and won't be allowed to GPL. 

That said, you can do a boxy chair, that's fine, just no identicals or derivatives.

**Comment by aerkiaga** [comment]
Good, I certainly didn't feel like modelling the copyrighted boxy chair. Maybe I'll add some more kinds of seats later tho.
