### ISSUE TITLE
Players can breathe in outer space (suggestion for inclusion of the vacuum mod)

### ISSUE THREAD

**Issue by corarona** [aerkiaga/nodeverse#15]
There is a pretty good mod with vacuum mechanics already  - basically it adds a new "vacuum" airlike node that suffocates the player. it includes air pumps and air bottles with which you can pressurize rooms.

it's compatible with the space suit mod

https://github.com/mt-mods/vacuum/
https://github.com/mt-mods/spacesuit

EDIT: i had mistakenly assumed the spacesuit is part of the vacuum mod. corrected that.

**Comment by aerkiaga** [comment]
This is already planned for 0.3 :) The exact implementation is still to be determined, but already having a mod for that is nice!

**Comment by aerkiaga** [comment]
While the exact outer space implementation is left for 0.3, there should be some restriction forbidding the player from being exposed to the space between planets. Like, forcing all spaceships to be closed spaces.

**Comment by aerkiaga** [comment]
0.3 was published with separate "space" and "planet" regions, and the player typically only accesses the former via a closed spaceship, so I'd say this issue can be closed.
