### ISSUE TITLE
Mind if I release rockets as a Mod on Content Database?

### ISSUE THREAD

**Issue by ExeVirus** [aerkiaga/nodeverse#19]
I am leaning towards MIT license for it, are you okay with that?

**Comment by aerkiaga** [comment]
Perfect for me! In the end, the mod is yours. Just put yourself as author, make sure that there's no other license stuff remaining and go ahead! :)

**Comment by aerkiaga** [comment]
The rocket mod is being maintained further in the v0.1 branch.
