### ISSUE TITLE
can not get rocket out of water if placed in water.

### ISSUE THREAD

**Issue by qwerty123a2** [aerkiaga/nodeverse#21]
if you place a rocket underneath you then you will be stuck.

**Comment by aerkiaga** [comment]
So, there are two problems here. First, the rocket cannot be right-clicked underwater; second, even if you click on a part sticking out of water, rocket thrust doesn't work underwater so you can't lift off. Both should be fixed now, I'll push the changes.

**Comment by aerkiaga** [comment]
I've created a new point release with this and other fixes. I'll keep working on 0.2.x as soon as I have the time.
